# Generated by Django 4.2.13 on 2024-07-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_ingredient_recipeingredient_recipecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
